openapi: 3.0.0
info:
  title: backend
  version: 1.0.0
  description: Athar Project Backend
servers:
  - url: http://localhost:3001/api

paths:
  /health:
    get:
      summary: Health Check
      description: Returns the health status of the server
      responses:
        "200":
          description: Server is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: OK
                  timestamp:
                    type: string
                    example: "2024-01-01T00:00:00.000Z"